import { useEffect, useMemo, useState } from "react";
import { FormControl, InputLabel, MenuItem, Select } from "@mui/material";
import TourismMap from "../../components/TourismMap/TourismMap";
import PlaceCard from "../../components/PlaceCard/PlaceCard";
import ExperienceCard from "../../components/ExperienceCard/ExperienceCard";
import { api } from "../../services/api";
import { tourismCategories } from "../../data/tourismCategories";
import "./MapPage.css";
export default function MapPage({favorites,onToggleFavorite}){const [places,setPlaces]=useState([]),[experiences,setExperiences]=useState([]),[category,setCategory]=useState('all');useEffect(()=>{Promise.all([api.getPlaces(),api.getExperiences()]).then(([p,e])=>{setPlaces(p.data);setExperiences(e.data)})},[]);const markers=useMemo(()=>category==='all'?[...places,...experiences]:places.filter(x=>x.category===category),[places,experiences,category]);return <div><section className="map-page__hero"><div className="container-custom"><span className="pill">Mapa turístico</span><h1>Explora Nicaragua sobre el mapa</h1><p>Filtra categorías y descubre cómo conectar lugares, experiencias y servicios dentro de un mismo recorrido.</p></div></section><section className="section"><div className="container-custom"><div className="map-page__toolbar"><FormControl size="small" sx={{minWidth:260}}><InputLabel>Categoría</InputLabel><Select label="Categoría" value={category} onChange={e=>setCategory(e.target.value)}><MenuItem value="all">Todas</MenuItem>{tourismCategories.map(c=><MenuItem key={c.key} value={c.key}>{c.label}</MenuItem>)}</Select></FormControl><span>{markers.length} marcadores en modo local</span></div><TourismMap places={markers} height={580}/><div className="map-page__grid">{markers.slice(0,12).map(item=>item.title?<ExperienceCard key={item.id} experience={item} isFavorite={favorites.includes(`experience:${item.id}`)||favorites.includes(item.id)} onToggleFavorite={onToggleFavorite}/>:<PlaceCard key={item.id} place={item} favorite={favorites.includes(`place:${item.id}`)||favorites.includes(item.id)} onToggleFavorite={onToggleFavorite}/>)}</div></div></section></div>}
