import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Button, TextField } from "@mui/material";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import ArrowUpwardRoundedIcon from "@mui/icons-material/ArrowUpwardRounded";
import ArrowDownwardRoundedIcon from "@mui/icons-material/ArrowDownwardRounded";
import { api } from "../../services/api";
import toast from "react-hot-toast";
import SmartImage from "../../components/common/SmartImage/SmartImage";
import "./MyTrip.css";
export default function MyTrip(){const [trip,setTrip]=useState({name:'Mi viaje a Nicaragua',items:[]});useEffect(()=>{api.getItinerary().then(setTrip)},[]);const persist=async(next)=>{setTrip(next);await api.saveItinerary(next)};const move=(i,d)=>{const next=[...trip.items];const j=i+d;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];persist({...trip,items:next})};const remove=id=>persist({...trip,items:trip.items.filter(x=>x.id!==id)});const clear=()=>persist({...trip,items:[]});return <div className="section"><div className="container-custom"><div className="trip-head"><div><span className="pill">Planificación local</span><h1>Mi viaje</h1><p>Organiza lugares y experiencias. Todo se guarda en tu navegador mientras el backend permanece desconectado.</p></div><div className="trip-head__actions"><TextField value={trip.name} onChange={e=>persist({...trip,name:e.target.value})} label="Nombre del itinerario" size="small"/><Button color="error" onClick={clear}>Vaciar</Button></div></div>{trip.items.length===0?<div className="trip-empty"><strong>Tu itinerario está vacío</strong><p>Explora destinos y usa “Agregar a Mi viaje”.</p><Link to="/explorar" className="waia-btn-primary">Explorar</Link></div>:<div className="trip-list">{trip.items.map((item,index)=><article className="trip-item" key={`${item.id}-${index}`}><SmartImage src={item.imageUrl} alt={item.name}/><div className="trip-item__content"><span className="pill">{item.type==='place'?'Lugar':'Experiencia'}</span><h3>{item.name}</h3><p>{item.municipality||''}{item.department?`, ${item.department}`:''}</p><div className="trip-item__actions"><Button size="small" startIcon={<ArrowUpwardRoundedIcon/>} onClick={()=>move(index,-1)}>Subir</Button><Button size="small" startIcon={<ArrowDownwardRoundedIcon/>} onClick={()=>move(index,1)}>Bajar</Button><Button size="small" color="error" startIcon={<DeleteOutlineRoundedIcon/>} onClick={()=>{remove(item.id);toast.success('Eliminado del itinerario')}}>Eliminar</Button></div></div></article>)}</div>}</div></div>}
