import { Link } from "react-router-dom";
import TravelExploreRoundedIcon from "@mui/icons-material/TravelExploreRounded";
import FacebookRoundedIcon from "@mui/icons-material/Facebook";
import InstagramIcon from "@mui/icons-material/Instagram";
import YouTubeIcon from "@mui/icons-material/YouTube";

export default function Footer() {
  return <footer className="bg-[#212121] px-6 py-12 text-white"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-3"><img src="/Logo-Waia.png" alt="WAIA" className="h-11 w-auto brightness-0 invert" /><span className="text-xl font-extrabold">WAIA</span></div><p className="mt-4 max-w-md leading-7 text-white/55">Conectamos viajeros con personas, comunidades y experiencias que mantienen viva la cultura de Nicaragua.</p><div className="mt-5 flex gap-2"><a href="https://facebook.com" target="_blank" rel="noreferrer" className="rounded-full bg-white/10 p-2 text-white"><FacebookRoundedIcon fontSize="small" /></a><a href="https://instagram.com" target="_blank" rel="noreferrer" className="rounded-full bg-white/10 p-2 text-white"><InstagramIcon fontSize="small" /></a><a href="https://youtube.com" target="_blank" rel="noreferrer" className="rounded-full bg-white/10 p-2 text-white"><YouTubeIcon fontSize="small" /></a></div></div><div><h3 className="font-extrabold">Explorar</h3><div className="mt-4 grid gap-3 text-sm text-white/60"><Link to="/" className="text-inherit no-underline hover:text-white">Inicio</Link><Link to="/experiencias" className="text-inherit no-underline hover:text-white">Experiencias</Link><Link to="/departamentos" className="text-inherit no-underline hover:text-white">Destinos</Link><Link to="/comunidades" className="text-inherit no-underline hover:text-white">Comunidades</Link></div></div><div><h3 className="font-extrabold">Información</h3><div className="mt-4 grid gap-3 text-sm text-white/60"><Link to="/como-funciona" className="text-inherit no-underline hover:text-white">Cómo funciona</Link><Link to="/favoritos" className="text-inherit no-underline hover:text-white">Favoritos</Link><Link to="/reservas" className="text-inherit no-underline hover:text-white">Mis reservas</Link><Link to="/contacto" className="text-inherit no-underline hover:text-white">Contacto</Link></div></div><div><div className="flex items-center gap-2 text-[#D50F35]"><TravelExploreRoundedIcon /><span className="font-extrabold">Turismo responsable</span></div><p className="mt-4 text-sm leading-6 text-white/55">Descubrir también significa apoyar a quienes mantienen vivas nuestras tradiciones.</p></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-xs text-white/40">© {new Date().getFullYear()} WAIA. Todos los derechos reservados.</div></footer>;
}
